### ISSUE TITLE
Does not work: The key and the hash do not match

### ISSUE THREAD

**Issue by paragonodyssey** [florianzeeb/keepass_keyfile_generator#1]
Tried generating keyfile using the script. Getting error while using the generated keyfile in KeePass: 

Failed to load the specified file! 

The key and the hash do not match, i.e. the key or the hash is invalid.

**Comment by florianzeeb** [comment]
Hi @paragonodyssey,

the KeePass Keyfile Generator script only generates keyfiles in a bulk. Bases on the created keyfiles you need to link 1 keyfile to your keepass.kdbx container. After that process you can access the container with your password and the selected/linked keyfile.

How to link the keyfile to a kdbx container? Open the existing keyfile, go to "File" -> "Change Mastere Key" -> "Show expert options" and select "Key file/provider" and chose the one you selected out from your created ones.

**Comment by florianzeeb** [comment]
Answer provided in posting above.

**Comment by paragonodyssey** [comment]
Thanks @florianzeeb . I got the above error in KeePass while trying to use one of the generated keyfiles for the database. I am using KeePass version 2.52 on Windows.

**Comment by florianzeeb** [comment]
@paragonodyssey thanks for your explanation and I can confirm there is some bug in regards of the keys and hash value. I need to check what is the issue to fix it.

**Comment by florianzeeb** [comment]
Bug has been fixed with the release of version 1.1.
